# Site settings
title: Cooking with Cast Iron
description: A short online course about cooking
url: "http://mateussmedeiros.github.io/blade-theme/" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author:
  name     : Brett Haines
  bio      : Masters degree student at Georgia Tech, investigating the effectiveness of online courses
  email    : bhaines3@gatech.edu

#SEO settings
logo: /assets/img/img-blog.png/ # Site logo URL

# Build settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/blog/page/:num"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed